### ISSUE TITLE
Any plan to port this theme to oh-my-fish public repo

### ISSUE THREAD

**Issue by orklann** [usami-k/graystatus#1]
There are some fish shell themes on [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish) public repo, do you have any plan to port this theme to it?

**Comment by usami-k** [comment]
I did not know well about oh-my-fish public repo. OK, I will try to add this theme to it.
Thank you for your notice.

**Comment by orklann** [comment]
Thanks.

**Comment by orklann** [comment]
Well done.  :)

**Comment by usami-k** [comment]
Thanks!
